### ISSUE TITLE
Typographical error - MAPClient UI- Image Segmentation Task 4

### ISSUE THREAD

**Issue by shsa992** [ABI-Tutorials/DTP-Segmentation#2]
The MAPClient tool has a typographical error on the UI for Task 4 under the Image Segmentation section. 
Attached is the snip.
![ui_typo_is_task4](https://user-images.githubusercontent.com/42825736/45933849-d021e400-bfe8-11e8-8fd3-a6e266b92cec.PNG)

**Comment by hsorby** [comment]
We do have a problem with the MAP Client in that the graph generated to determine execution is non-deterministic.  This is most readily seen in workflows that have more than one independent initial step, one execution can have a different order of steps from the next.  So what you are probably seeing here is an order of execution that is different to the documented order, there is nothing we can do about this at this stage until a fix is applied to MAP Client itself.  A note is the best we can do, and to make sure we mention it in the MAP Client introduction.

**Comment by nickerso** [comment]
I think the error here is actually the typo in the title of the widget ``Heart Tra&nsform Tools`` - perhaps a quick-key combo not getting picked up?

**Comment by hsorby** [comment]
I need a higher resolution screen!

**Comment by hsorby** [comment]
Probably a copy and paste from a menu item property.

**Comment by hsorby** [comment]
Fixed in commit https://github.com/mapclient-plugins/hearttransform/commit/8d04168547076e7d1f5f6cd21c525a05a98f0ed6.

**Comment by shsa992** [comment]
Thanks David for clarifying my point and Thanks Hugh for fixing it.
